language: go

go:
  - 1.x

os:
  - linux

install:
  - go get -t ./...
  - go get -u github.com/golang/lint/golint

script:
  - ./travis-ci/codecheck.sh
  - go test -cpu=2 -race -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
